#!/bin/bash

# Install Oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Function to add a plugin to .zshrc if it's not already added
add_plugin() {
    local plugin_name="$1"
    local zshrc_path="$HOME/.zshrc"
    local plugins_line
    if [ -f "$zshrc_path" ]; then
        plugins_line=$(grep -o "plugins=([^)]*" "$zshrc_path" | sed -n '2p')
        if [[ -n "$plugins_line" ]]; then
            if ! echo "$plugins_line" | grep -q "$plugin_name"; then
                sed -i "s/$plugins_line/plugins=($plugins_line $plugin_name)/" "$zshrc_path"
                echo "Added '$plugin_name' to the plugins in $zshrc_path"
            else
                echo "'$plugin_name' is already in the plugins list in $zshrc_path"
            fi
        else
            echo "No second 'plugins' line found in $zshrc_path. Adding one."
            echo "plugins=($plugin_name)" >> "$zshrc_path"
        fi
    else
        echo "Warning: $zshrc_path not found."
    fi
}

# Install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
add_plugin "zsh-syntax-highlighting"

# Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
add_plugin "zsh-autosuggestions"

# Install Powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Set ZSH_THEME to Powerlevel10k
zshrc_path="$HOME/.zshrc"
if [ -f "$zshrc_path" ]; then
    sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$zshrc_path"
    echo "Set ZSH_THEME to Powerlevel10k in $zshrc_path"
else
    echo "Warning: $zshrc_path not found."
fi

echo "Make sure to restart your shell or run 'source ~/.zshrc' for changes to take effect."
